### ISSUE TITLE
Minimal energy needed for growth constraint

### ISSUE THREAD

**Issue by gregorykimmel** [MathOnco/ploidyEvolution#21]
Add minimum energy threshold (e.g. 100 hours doubling time) for growth to occur.

**Comment by noemiandor** [comment]
It's minimum birth rate rather than minimum energy threshold, no? Motivation was that if the cell cycle (more specifically the G1 phase of the cell cycle) lasts long, then the cell enters G0 (quiescence) and effectively no longer divides.

**Comment by noemiandor** [comment]
Code contains two comparisons of birthRate to threshold: `energy_modified_birth_rate > log(2)/max_cell_cycle_duration`  However, log2 is only in there for the first comparison, not the second.

**Comment by noemiandor** [comment]
Code contains two comparisons of birthRate to threshold: `energy_modified_birth_rate > log(2)/max_cell_cycle_duration` However, log2 is only in there for the first comparison, not the second.
