### ISSUE TITLE
conservation of cell number incorrect after misseg?

### ISSUE THREAD

**Issue by Richard-Beck** [MathOnco/ploidyEvolution#26]
line 301 ploidymovement.jl
check if correct:
`val = misRate/nChrom`
Since each parent can have  2*nChrom daughter states, consider:
`val = 0.5*misRate/nChrom`

**Comment by gregorykimmel** [comment]
The current q assumes that acceptable moves involve only a single change in the new chromosome set. You have nChrom possible missegregations and so it should be misRate/nChrom. The alternative way of thinking (as you have it) is fine as well, but you now need to count twice as there are "two" events which lead to parent -> offspring, one in which offspring A gets there and one in which offspring B gets there so it would be val = 0.5*misRate/nChrom*2.

**Comment by Richard-Beck** [comment]
OK I understand that although each parent can have 2*nChrom offspring, in reality there are only nChrom possible unique events because each event generates two different offspring. Therefore the current q was indeed already correct.
